// <auto-generated />
using System;
using AgenciaDeViajes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgenciaDeViajes.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250614121459_CrearTablaReviews")]
    partial class CrearTablaReviews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgenciaDeViajes.Models.Actividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("EventoId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("HoraFin")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<int>("IdEvento")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("AgenciaDeViajes.Models.Destino", b =>
                {
                    b.Property<int>("id_destino")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_destino");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_destino"));

                    b.Property<string>("ImgDest_url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ImgDest_url");

                    b.Property<string>("desc_destino")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("desc_destino");

                    b.Property<int>("id_region")
                        .HasColumnType("integer")
                        .HasColumnName("id_region");

                    b.Property<string>("nom_destino")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nom_destino");

                    b.Property<int>("num_entradas")
                        .HasColumnType("integer")
                        .HasColumnName("num_entradas");

                    b.Property<decimal>("precio_tour")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_tour");

                    b.Property<string>("time_tour")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("time_tour");

                    b.HasKey("id_destino");

                    b.HasIndex("id_region");

                    b.ToTable("Destinos");
                });

            modelBuilder.Entity("AgenciaDeViajes.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("FestividadId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("Hora")
                        .HasColumnType("interval");

                    b.Property<int>("IdFestividad")
                        .HasColumnType("integer");

                    b.Property<string>("Lugar")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FestividadId");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("AgenciaDeViajes.Models.Festividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("text");

                    b.Property<string>("Lugar")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Festividades");
                });

            modelBuilder.Entity("AgenciaDeViajes.Models.PasajeroReserva", b =>
                {
                    b.Property<int>("IdPasajero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdPasajero");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPasajero"));

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Documento");

                    b.Property<int>("IdReserva")
                        .HasColumnType("integer")
                        .HasColumnName("IdReserva");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NombreCompleto");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Pais");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Telefono");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Tipo");

                    b.HasKey("IdPasajero");

                    b.HasIndex("IdReserva");

                    b.ToTable("PasajerosReserva");
                });

            modelBuilder.Entity("AgenciaDeViajes.Models.Region", b =>
                {
                    b.Property<int>("id_region")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_region"));

                    b.Property<string>("ImgReg_url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("desc_region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("num_tours")
                        .HasColumnType("integer");

                    b.HasKey("id_region");

                    b.ToTable("Regiones");
                });

            modelBuilder.Entity("AgenciaDeViajes.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdReserva");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdReserva"));

                    b.Property<int>("CantidadAdultos")
                        .HasColumnType("integer")
                        .HasColumnName("CantidadAdultos");

                    b.Property<int>("CantidadNinos")
                        .HasColumnType("integer")
                        .HasColumnName("CantidadNinos");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("Estado");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp")
                        .HasColumnName("FechaPago");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("timestamp")
                        .HasColumnName("FechaReserva");

                    b.Property<DateTime>("FechaTour")
                        .HasColumnType("timestamp")
                        .HasColumnName("FechaTour");

                    b.Property<int>("IdDestino")
                        .HasColumnType("integer")
                        .HasColumnName("IdDestino");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("IdUsuario");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("MetodoPago");

                    b.Property<decimal>("PrecioTotal")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("PrecioTotal");

                    b.Property<string>("ReferenciaPago")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ReferenciaPago");

                    b.HasKey("IdReserva");

                    b.HasIndex("IdDestino");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("AgenciaDeViajes.Models.ReservaServicioAdicional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdReserva")
                        .HasColumnType("integer")
                        .HasColumnName("IdReserva");

                    b.Property<string>("Servicio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Servicio");

                    b.HasKey("Id");

                    b.HasIndex("IdReserva");

                    b.ToTable("ReservaServiciosAdicionales");
                });

            modelBuilder.Entity("AgenciaDeViajes.Models.Review", b =>
                {
                    b.Property<int>("IdReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdReview"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CalificacionAtencion")
                        .HasColumnType("integer");

                    b.Property<int>("CalificacionCalidad")
                        .HasColumnType("integer");

                    b.Property<int>("CalificacionPuntualidad")
                        .HasColumnType("integer");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdDestino")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Sentimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdReview");

                    b.HasIndex("IdDestino");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("AgenciaDeViajes.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreCompleto")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AgenciaDeViajes.Models.Actividad", b =>
                {
                    b.HasOne("AgenciaDeViajes.Models.Evento", "Evento")
                        .WithMany("Actividades")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("AgenciaDeViajes.Models.Destino", b =>
                {
                    b.HasOne("AgenciaDeViajes.Models.Region", "Region")
                        .WithMany("Destinos")
                        .HasForeignKey("id_region")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("AgenciaDeViajes.Models.Evento", b =>
                {
                    b.HasOne("AgenciaDeViajes.Models.Festividad", "Festividad")
                        .WithMany("Eventos")
                        .HasForeignKey("FestividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Festividad");
                });

            modelBuilder.Entity("AgenciaDeViajes.Models.PasajeroReserva", b =>
                {
                    b.HasOne("AgenciaDeViajes.Models.Reserva", "Reserva")
                        .WithMany("PasajerosReserva")
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("AgenciaDeViajes.Models.Reserva", b =>
                {
                    b.HasOne("AgenciaDeViajes.Models.Destino", "Destino")
                        .WithMany()
                        .HasForeignKey("IdDestino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destino");
                });

            modelBuilder.Entity("AgenciaDeViajes.Models.ReservaServicioAdicional", b =>
                {
                    b.HasOne("AgenciaDeViajes.Models.Reserva", "Reserva")
                        .WithMany("ReservaServiciosAdicionales")
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("AgenciaDeViajes.Models.Review", b =>
                {
                    b.HasOne("AgenciaDeViajes.Models.Destino", "Destino")
                        .WithMany()
                        .HasForeignKey("IdDestino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgenciaDeViajes.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destino");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AgenciaDeViajes.Models.Evento", b =>
                {
                    b.Navigation("Actividades");
                });

            modelBuilder.Entity("AgenciaDeViajes.Models.Festividad", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("AgenciaDeViajes.Models.Region", b =>
                {
                    b.Navigation("Destinos");
                });

            modelBuilder.Entity("AgenciaDeViajes.Models.Reserva", b =>
                {
                    b.Navigation("PasajerosReserva");

                    b.Navigation("ReservaServiciosAdicionales");
                });
#pragma warning restore 612, 618
        }
    }
}
